var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__12v6k56._.js")
R.c("server/chunks/ssr/00u8_next_dist_17fza-h._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zqkwuv._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0iu-e5i._.js")
R.c("server/chunks/ssr/apps_hub_app_layout_tsx_0bw3fat._.js")
R.c("server/chunks/ssr/00u8_next_dist_client_components_0444poz._.js")
R.c("server/chunks/ssr/00u8_next_dist_client_components_builtin_forbidden_1zzaejh.js")
R.c("server/chunks/ssr/00u8_next_dist_client_components_builtin_unauthorized_0m6z7qj.js")
R.c("server/chunks/ssr/00u8_next_dist_client_components_builtin_global-error_12tp96_.js")
R.c("server/chunks/ssr/apps_hub__next-internal_server_app_page_actions_0nadt2u.js")
R.m(3081)
module.exports=R.m(3081).exports
