import type { Locale } from "@/db/schema";

const m = {
  ca: { title: "Cookies i privacitat", text: "Fem servir només l'emmagatzematge imprescindible perquè el web funcioni. Amb el teu permís, també podem recordar la campanya d'origen i carregar contingut extern (YouTube, Adobe).", acceptAll: "Acceptar-ho tot", rejectAll: "Rebutjar-ho tot", configure: "Configurar", dialogTitle: "Preferències de cookies", save: "Desa les preferències", always: "Sempre activades", close: "Tanca", cookieList: "Cookies i emmagatzematge que fem servir", colName: "Nom", colCategory: "Categoria", colPurpose: "Finalitat", colDuration: "Durada", colProvider: "Proveïdor", change: "Canvia les preferències", allowEmbeds: "Permet sempre el contingut extern" },
  es: { title: "Cookies y privacidad", text: "Solo usamos el almacenamiento imprescindible para que la web funcione. Con tu permiso, también podemos recordar la campaña de origen y cargar contenido externo (YouTube, Adobe).", acceptAll: "Aceptar todo", rejectAll: "Rechazar todo", configure: "Configurar", dialogTitle: "Preferencias de cookies", save: "Guardar preferencias", always: "Siempre activadas", close: "Cerrar", cookieList: "Cookies y almacenamiento que utilizamos", colName: "Nombre", colCategory: "Categoría", colPurpose: "Finalidad", colDuration: "Duración", colProvider: "Proveedor", change: "Cambiar las preferencias", allowEmbeds: "Permitir siempre el contenido externo" },
  en: { title: "Cookies and privacy", text: "We only use the storage the site needs to work. With your permission we can also remember which campaign you came from and load external content (YouTube, Adobe).", acceptAll: "Accept all", rejectAll: "Reject all", configure: "Settings", dialogTitle: "Cookie preferences", save: "Save preferences", always: "Always on", close: "Close", cookieList: "Cookies and storage we use", colName: "Name", colCategory: "Category", colPurpose: "Purpose", colDuration: "Duration", colProvider: "Provider", change: "Change preferences", allowEmbeds: "Always allow external content" },
} as const;
export const consentMsgs = (l: Locale) => m[l];
export type ConsentMsgs = (typeof m)["ca"];
